workflows:
  auto_deploy:
    steps:
      - check_health
      - build_containers
      - fly_deploy
  auto_training:
    steps:
      - collect_chat_logs
      - run_preprocessor
      - train_model_checkpoint
