app = "mezo-ai"
primary_region = "ord"
[build]
  dockerfile = "../../mezo-indexer/Dockerfile"
[env]
  MEZO_APP_NAME = "mezo-ai"
[processes]
  indexer = ""
[mounts]
  source = "mezo_index_data"
  destination = "/index"
[checks.http]
  type = "http"
  port = 8080
  path = "/healthz"
  interval = "15s"
  timeout = "5s"
[[vm]]
  size = "performance-4x"
  memory = "32gb"
[[services]]
  internal_port = 8080
  protocol = "tcp"
  processes = ["indexer"]
[[services.ports]]
  port = 8080
